server:
  port: 8080

fisketegn:
  api:
    path: '/camel'

camel:
  springboot:
    name: ServicesRest

Management:
  port: 8081

endpoints:
  enabled: false
  health:
    enabled: true

quickstart:
  generateOrderPeriod: 10s
  processorderPeriod: 30s

jwtSecure:
  key: '<ZY3MK:ctPh=jIW|=QtC|4w{)_P,xdQa{_Ex$+yM]YR|s5\\2+Nq/GWM)xJwZ|m#L'

licenseNumber:
  number: -1

email:
  password: fiskepassword